/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://ercktpcqzfb5dazhuzzstufu6i.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-tjpllsb2qbeihdfiqjkn3vgnpq",
    "aws_cognito_identity_pool_id": "us-east-2:4dd6b7c9-b9ae-414b-9656-4904d6564c50",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_KkKh4n3cG",
    "aws_user_pools_web_client_id": "68tkgh229n0oh30gtgks4b58gm",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "EMAIL"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
