/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://7rt525cpz5a5ddntswdjs4o36u.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-noj6sf44szgn3pvoacpqezgphq",
    "aws_cognito_identity_pool_id": "us-east-2:c9c30415-d796-4523-8bdb-be3c9ce9788a",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_s87AHVd0F",
    "aws_user_pools_web_client_id": "nrld4pg0dglbulpkannkv6mrf",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "EMAIL"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
